apiVersion : apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment-{{ .Values.env}}"
  labels:
    app : "{{ .Release.Name }}-deployment-{{ .Values.env}}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }} 
    spec:
      volumes:
      - name: {{ .Values.volumesname}}
        secret:
          secretName: {{ .Values.secretname}}
      containers:
        - name : "{{ .Release.Name }}-web"
          image: "{{ .Values.container.image}}-{{ .Values.env}}:{{ .Values.container.tag }}"
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-configmap"
          resources:
          {{- toYaml .Values.container.resources | nindent 4}}
          ports: 
            - containerPort: {{ .Values.container.containerPort}}
