apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rental-ingress
spec:
  rules:
    - host: {{ .Values.env}}.{{ .Values.ingress.host}}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-service-{{ .Values.env}}
            servicePort: 80