apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rental-ingress
spec:
  rules:
    - host: {{ .Values.ingress.host.dev}}
      http:
        paths:
          backend:
            serviceName: rental-service-dev
            servicePort: 80
    - host: {{ .Values.ingress.host.prod}}
      http:
        paths:
          backend:
            serviceName: rental-service-prod
            servicePort: 80