apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rental-ingress
spec:
  rules:
    - host: {{ .Values.ingress.host.dev}}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-service-dev
            servicePort: 80